[project]
name = "docmail-assistant"
version = "0.1.0"
description = "An AI assistant for drafting medical emails using RAG."

[tool.setuptools.packages.find]
where = ["."]  # Look for packages in the current directory (the 'docmail' root)
exclude = ["data*", "frontend*"]
